### ISSUE TITLE
Heroku push fails, both during and after setup

### ISSUE THREAD

**Issue by danicastone** [RailsApps/rails-stripe-checkout#2]
Noticed this string of error messages during setup; tried to install it twice and got errors both times. It looks like each one is a failure of a rake task, with "KeyError: key not found: "MAILCHIMP_API_KEY"".

init
        init  recipe stage three
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
        gsub    config/initializers/devise.rb
      remove    db/seeds.rb
      create    db/seeds.rb
      remove    app/services/create_admin_service.rb
      create    app/services/create_admin_service.rb
        init  applying migrations and seeding the database
         run    bundle exec rake db:migrate from "."
rake aborted!
KeyError: key not found: "MAILCHIMP_API_KEY"
(erb):20:in `fetch'
(erb):20:in`<main>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:391:in `secrets'
/home/ubuntu/workspace/hydraulicelectro/config/environments/development.rb:33:in`block in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `instance_eval'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/railtie.rb:210:in`configure'
/home/ubuntu/workspace/hydraulicelectro/config/environments/development.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in`load_dependency'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:598:in`block (2 levels) in class:Engine'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:597:in `each'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:597:in`block in class:Engine'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:30:in`run'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:44:in`each'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:54:in`run_initializers'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
/home/ubuntu/workspace/hydraulicelectro/config/environment.rb:5:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`block in require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:457:in`block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/bin/ruby_executable_hooks:15:in`<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
         run    bundle exec rake db:seed from "."
rake aborted!
KeyError: key not found: "MAILCHIMP_API_KEY"
(erb):20:in `fetch'
(erb):20:in`<main>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:391:in `secrets'
/home/ubuntu/workspace/hydraulicelectro/config/environments/development.rb:33:in`block in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `instance_eval'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/railtie.rb:210:in`configure'
/home/ubuntu/workspace/hydraulicelectro/config/environments/development.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in`load_dependency'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:598:in`block (2 levels) in class:Engine'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:597:in `each'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:597:in`block in class:Engine'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:30:in`run'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:44:in`each'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:54:in`run_initializers'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
/home/ubuntu/workspace/hydraulicelectro/config/environment.rb:5:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`block in require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:457:in`block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:179:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/bin/ruby_executable_hooks:15:in`eval'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:abort_if_pending_migrations => environment
(See full trace by running task with --trace)
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: set up database" from "."
    generate    layout:devise bootstrap3 -f
(erb):20:in`fetch': key not found: "MAILCHIMP_API_KEY" (KeyError)
        from (erb):20:in `<main>'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/erb.rb:850:in`eval'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/erb.rb:850:in `result'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:391:in`secrets'
        from /home/ubuntu/workspace/hydraulicelectro/config/environments/development.rb:33:in `block in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/railtie.rb:210:in`instance_eval'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `configure'
        from /home/ubuntu/workspace/hydraulicelectro/config/environments/development.rb:1:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`block in require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:597:in`each'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:30:in`instance_exec'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:55:in`block in run_initializers'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:348:in`block (2 levels) in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:427:in`each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:44:in`each'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:411:in`call'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:347:in`block in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in`call'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:224:in`tsort_each'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:54:in`run_initializers'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
        from /home/ubuntu/workspace/hydraulicelectro/config/environment.rb:5:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`block in require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:142:in`require_application_and_environment!'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:50:in`generate'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/commands.rb:17:in`<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in`<main>'
    generate    layout:navigation -f
(erb):20:in `fetch': key not found: "MAILCHIMP_API_KEY" (KeyError)
        from (erb):20:in`<main>'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/erb.rb:850:in `eval'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/erb.rb:850:in`result'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:391:in `secrets'
        from /home/ubuntu/workspace/hydraulicelectro/config/environments/development.rb:33:in`block in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `instance_eval'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/railtie.rb:210:in`configure'
        from /home/ubuntu/workspace/hydraulicelectro/config/environments/development.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in`load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:598:in`block (2 levels) in class:Engine'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:597:in `each'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:597:in`block in class:Engine'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:30:in`run'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:226:in`block in tsort_each'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:418:in`block (2 levels) in each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:417:in`block in each_strongly_connected_component_from'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:44:in`tsort_each_child'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:411:in `call'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:411:in`each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in`each'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `call'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in`each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:205:in`tsort_each'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:352:in`initialize!'
        from /home/ubuntu/workspace/hydraulicelectro/config/environment.rb:5:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in`load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:328:in`require_environment!'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:128:in`generate_or_destroy'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in`run_command!'
        from /usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in`require'
        from bin/rails:4:in `<main>'
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: navigation links" from "."
On branch master
nothing to commit, working directory clean
deployment
  deployment  recipe stage three
  deployment  precompiling assets for Heroku
         run    RAILS_ENV=production rake assets:precompile from "."
rake aborted!
KeyError: key not found: "MAILCHIMP_API_KEY"
(erb):20:in`fetch'
(erb):20:in `<main>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:391:in`secrets'
/home/ubuntu/workspace/hydraulicelectro/config/environments/production.rb:77:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/railtie.rb:210:in`instance_eval'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `configure'
/home/ubuntu/workspace/hydraulicelectro/config/environments/production.rb:1:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`block in require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:597:in`each'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:30:in`instance_exec'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:55:in`block in run_initializers'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:44:in`tsort_each_child'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:352:in`initialize!'
/home/ubuntu/workspace/hydraulicelectro/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in`load_dependency'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:328:in`require_environment!'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/railties-4.2.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5@hydraulicelectro/gems/sprockets-rails-2.3.1/lib/sprockets/rails/task.rb:64:in`block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)

**Comment by danicastone** [comment]
Hmm -- tried deleting the whole thing and giving Heroku all the environmental variables before I ran 'rails new rails-stripe-checkout -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb'. That fixed all the errors above, but I'm left with this oddball that seems to be coming from devise.rb:

  deployment  recipe stage three
  deployment  precompiling assets for Heroku
         run    RAILS_ENV=production rake assets:precompile from "."
rake aborted!
TypeError: no implicit conversion of nil into String

and it won't push up to Heroku -- just gives me the same error when I try.

If I tell it not to prepare for deployment, during setup, I get no error messages during setup itself, but get "Push rejected, no Cedar-supported app detected" when pushing to Heroku afterwards. (After setting up the correct repository, and pushing it up to github successfully. It says "HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically," but if I try to set it by hand again, it tells me "The buildpack https://github.com/heroku/heroku-buildpack-ruby is already set on your app.")

**Comment by kathyonu** [comment]
With this search phrase at startpage.com http://startpage.com/ : 

  No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

I found this answer : 

  http://stackoverflow.com/questions/18452701/ruby-on-rails-no-rakefile-found-error http://stackoverflow.com/questions/18452701/ruby-on-rails-no-rakefile-found-error

Also, make sure you are running the Heroku commands from within your working directory.
And ...
If you haven’t already done it this way ..
  and it appears from your note that you have ..
May I recommend you run just this in the app first, to get it ready.
Then you don’t have to run the the statement with “.”
or, is that being run by Devise itself ?

> On May 26, 2015, at 4:43 PM, danicastone notifications@github.com wrote:
> 
>  RAILS_ENV=production rake assets:precompile

Does this succeed ?
And can you now succeed with Heroku ?

If you have any difficulty with that command, 
 try removing old compiled assets, if any with : 

rake assets:clean

rake assets:clobber

rake -T     # for explanations of those two
